# Kafka config
kafka:
  client_id: iot_battlefield_bases
  topic_data: iot_battlefield_bases
  topic_move: ""

# Bases types and locations
bases:
  base_01:
    name: Fort Arsenal
    type: ammunition
    latitude: 48.54488969187439
    longitude: 39.33393150574515
  base_02:
    name: Provision Point
    type: food
    latitude: 48.554804290813244
    longitude: 39.34616237818907
  base_03:
    name: Equipment Depot
    type: equipment
    latitude: 48.53889453648839
    longitude: 39.3488231293874
  base_04:
    name: Medicor
    type: medical
    latitude: 48.53770110328317
    longitude: 39.359036980761616
