#######################
# Kafka configuration #
#######################
kafka:
  bootstrap.servers: broker:9094


##################################
# Schjema Registry configuration #
##################################
schema-registry:
  url: http://schema-registry:8081
