# Kafka config
kafka:
  client_id: iot_battlefield_tanks
  topic_data: iot_battlefield_tanks
  topic_move: iot_battlefield_tanks_moves

# Tanks deployment
deployment:
  number_of_units: 50
  start_latitude: 48.5456
  start_longitude: 39.3423
  bearing_angle_min: -5
  bearing_angle_max: 5
  distance_between_units: 20
  bearing_angle_between_units: -90
  seconds_between_moves: 30
  damage_probability_min: 1
  damage_probability_max: 5
  damage_impact_min: 1
  damage_impact_max: 5

# Tanks models
models:
  Challenger2:
    proportion: 20
    moving_speed_kph_min: 10
    moving_speed_kph_max: 40
    ammunition_min: 250
    ammunition_max: 500
    ammunition_rpm_min: 0.01
    ammunition_rpm_max: 0.05
    damage_can_support_min: 50
    damage_can_support_max: 75
  Warrior:
    proportion: 20
    moving_speed_kph_min: 10
    moving_speed_kph_max: 40
    ammunition_min: 250
    ammunition_max: 500
    ammunition_rpm_min: 0.01
    ammunition_rpm_max: 0.05
    damage_can_support_min: 50
    damage_can_support_max: 75
  Bulldog:
    proportion: 20
    moving_speed_kph_min: 10
    moving_speed_kph_max: 40
    ammunition_min: 250
    ammunition_max: 500
    ammunition_rpm_min: 0.01
    ammunition_rpm_max: 0.05
    damage_can_support_min: 50
    damage_can_support_max: 75
  FV430:
    proportion: 20
    moving_speed_kph_min: 10
    moving_speed_kph_max: 40
    ammunition_min: 250
    ammunition_max: 500
    ammunition_rpm_min: 0.01
    ammunition_rpm_max: 0.05
    damage_can_support_min: 50
    damage_can_support_max: 75
  Stormer:
    proportion: 20
    moving_speed_kph_min: 10
    moving_speed_kph_max: 40
    ammunition_min: 250
    ammunition_max: 500
    ammunition_rpm_min: 0.01
    ammunition_rpm_max: 0.05
    damage_can_support_min: 50
    damage_can_support_max: 75
