# Kafka config
kafka:
  client_id: iot_battlefield_tanks
  topic_data: iot_battlefield_tanks
  topic_move: iot_battlefield_tanks_moves

# Tanks deployment
deployment:
  seconds_between_moves: 30
  units:
    Luhansk:
      number_of_units: 50
      start_latitude: 48.5456
      start_longitude: 39.3423
      bearing_angle_min: -5
      bearing_angle_max: 5
      distance_between_units: -20
      bearing_angle_between_units: 90
      damage_probability_min: 1
      damage_probability_max: 5
      damage_impact_min: 1
      damage_impact_max: 5
    Mariupol:
      number_of_units: 50
      start_latitude: 47.0821
      start_longitude: 37.5152
      bearing_angle_min: -5
      bearing_angle_max: 5
      distance_between_units: -30
      bearing_angle_between_units: 90
      damage_probability_min: 1
      damage_probability_max: 5
      damage_impact_min: 1
      damage_impact_max: 5

# Tanks models
models:
  Challenger2:
    proportion: 20
    moving_speed_kph_mean: 25
    moving_speed_kph_stdev: 5
    ammunition_mean: 350
    ammunition_stdev: 10
    ammunition_rpm_mean: 1
    ammunition_rpm_stdev: 0.5
    damage_can_support_mean: 65
    damage_can_support_stdev: 5
  Warrior:
    proportion: 20
    moving_speed_kph_mean: 25
    moving_speed_kph_stdev: 5
    ammunition_mean: 350
    ammunition_stdev: 10
    ammunition_rpm_mean: 1
    ammunition_rpm_stdev: 0.5
    damage_can_support_mean: 65
    damage_can_support_stdev: 5
  Bulldog:
    proportion: 20
    moving_speed_kph_mean: 25
    moving_speed_kph_stdev: 5
    ammunition_mean: 350
    ammunition_stdev: 10
    ammunition_rpm_mean: 1
    ammunition_rpm_stdev: 0.5
    damage_can_support_mean: 65
    damage_can_support_stdev: 5
  FV430:
    proportion: 20
    moving_speed_kph_mean: 25
    moving_speed_kph_stdev: 5
    ammunition_mean: 350
    ammunition_stdev: 10
    ammunition_rpm_mean: 1
    ammunition_rpm_stdev: 0.5
    damage_can_support_mean: 65
    damage_can_support_stdev: 5
  Stormer:
    proportion: 20
    moving_speed_kph_mean: 25
    moving_speed_kph_stdev: 5
    ammunition_mean: 350
    ammunition_stdev: 10
    ammunition_rpm_mean: 1
    ammunition_rpm_stdev: 0.5
    damage_can_support_mean: 65
    damage_can_support_stdev: 5
